name: androidworld
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - android-env==1.2.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - av==14.4.0
      - babel==2.17.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.2.1
      - comm==0.2.2
      - conda-pack==0.8.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - dm-env==1.6
      - dm-tree==0.1.9
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flask==3.1.1
      - fonttools==4.57.0
      - fqdn==1.5.1
      - fsspec==2025.5.1
      - fuzzywuzzy==0.18.0
      - google-ai-generativelanguage==0.6.2
      - google-api-core==2.24.2
      - google-api-python-client==2.168.0
      - google-auth==2.39.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.5.1
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - grpcio-status==1.62.3
      - grpcio-tools==1.62.3
      - h11==0.16.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - idna==3.10
      - immutabledict==2.0.0
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==9.2.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - levenshtein==0.27.1
      - markupsafe==3.0.2
      - matplotlib==3.6.1
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - notebook==7.4.3
      - notebook-shim==0.2.4
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - openai==1.82.1
      - opencv-python==4.11.0.86
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pluggy==1.5.0
      - portpicker==1.6.0
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygame==2.6.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pyrsistent==0.20.0
      - pytesseract==0.3.13
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - python-levenshtein==0.27.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - qwen-vl-utils==0.0.11
      - rapidfuzz==3.13.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.25.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.14.0
      - tenacity==9.1.2
      - termcolor==3.0.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - torch==2.7.1
      - torchvision==0.22.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.4
      - triton==3.3.1
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
prefix: /home/androidworld/miniconda3/envs/androidworld
